export default [
  {
    title: 'UX UI Designer',
    company_name: 'Great vibes -Information Technology',
    location: 'Chennai, Tamilnadu',
    job_type: 'In-office',
    job_nature: 'Part-Time',
    'office-timing': '9.00 am - 5.00 pm IST',
    experience: '1-2 years',
    salary: '30,000 - 60,000 / Month',
    employees: '51-200 employees',
  },
  {
    title: 'Developer',
    company_name: 'Great vibes -Information Technology',
    location: 'Chennai, Tamilnadu',
    job_type: 'In-office',
    job_nature: 'Part-Time',
    'office-timing': '9.00 am - 5.00 pm IST',
    experience: '1-2 years',
    salary: '50,000 - 70,000 / Month',
    employees: '51-200 employees',
  },
  {
    title: 'Interaction Designer',
    company_name: 'Great vibes -Information Technology',
    location: 'Chennai, Tamilnadu',
    job_type: 'In-office',
    job_nature: 'Part-Time',
    'office-timing': '9.00 am - 5.00 pm IST',
    experience: '1-2 years',
    salary: '30,000 - 50,000 / Month',
    employees: '51-200 employees',
  },
  {
    title: 'SEO Analyst',
    company_name: 'Great vibes -Information Technology',
    location: 'Chennai, Tamilnadu',
    job_type: 'In-office',
    job_nature: 'Part-Time',
    'office-timing': '9.00 am - 5.00 pm IST',
    experience: '1-2 years',
    salary: '30,000 - 50,000 / Month',
    employees: '51-200 employees',
  },
];
